use super::super::ActionTemplate::{BookmarkFilterChar, PushSelectFilterChar};
use super::super::ModeId::{
    BookmarkPicker, BookmarkSelect, ClipboardBranchSelect, Conflicts, MovingBookmark, PushSelect,
    Rebase, Squash,
};
use super::super::{BindingBehavior, BindingSpec, CommandSpec, KeyDef};
use super::{fixed, single};
use crate::cmd::jj_tui::action::Action;
use ratatui::crossterm::event::KeyCode;

pub(super) fn commands() -> Vec<CommandSpec> {
    vec![
        BindingSpec::new(
            Rebase,
            "dest_down",
            fixed(Action::MoveRebaseDestDown),
            vec![
                single(KeyDef::Char('j')),
                single(KeyDef::Key(KeyCode::Down)),
            ],
        ),
        BindingSpec::new(
            Rebase,
            "dest_up",
            fixed(Action::MoveRebaseDestUp),
            vec![single(KeyDef::Char('k')), single(KeyDef::Key(KeyCode::Up))],
        ),
        BindingSpec::new(
            Rebase,
            "branches",
            fixed(Action::ToggleRebaseBranches),
            vec![single(KeyDef::Char('b'))],
        ),
        BindingSpec::new(
            Rebase,
            "run",
            fixed(Action::ExecuteRebase),
            vec![single(KeyDef::Key(KeyCode::Enter))],
        ),
        BindingSpec::new(
            Rebase,
            "cancel",
            fixed(Action::ExitRebaseMode),
            vec![single(KeyDef::Key(KeyCode::Esc))],
        ),
        BindingSpec::new(
            Squash,
            "dest_down",
            fixed(Action::MoveSquashDestDown),
            vec![
                single(KeyDef::Char('j')),
                single(KeyDef::Key(KeyCode::Down)),
            ],
        ),
        BindingSpec::new(
            Squash,
            "dest_up",
            fixed(Action::MoveSquashDestUp),
            vec![single(KeyDef::Char('k')), single(KeyDef::Key(KeyCode::Up))],
        ),
        BindingSpec::new(
            Squash,
            "run",
            fixed(Action::ExecuteSquash),
            vec![single(KeyDef::Key(KeyCode::Enter))],
        ),
        BindingSpec::new(
            Squash,
            "cancel",
            fixed(Action::ExitSquashMode),
            vec![single(KeyDef::Key(KeyCode::Esc))],
        ),
        BindingSpec::new(
            MovingBookmark,
            "dest_down",
            fixed(Action::MoveBookmarkDestDown),
            vec![
                single(KeyDef::Char('j')),
                single(KeyDef::Key(KeyCode::Down)),
            ],
        ),
        BindingSpec::new(
            MovingBookmark,
            "dest_up",
            fixed(Action::MoveBookmarkDestUp),
            vec![single(KeyDef::Char('k')), single(KeyDef::Key(KeyCode::Up))],
        ),
        BindingSpec::new(
            MovingBookmark,
            "run",
            fixed(Action::ExecuteBookmarkMove),
            vec![single(KeyDef::Key(KeyCode::Enter))],
        ),
        BindingSpec::new(
            MovingBookmark,
            "cancel",
            fixed(Action::ExitBookmarkMode),
            vec![single(KeyDef::Key(KeyCode::Esc))],
        ),
        BindingSpec::new(
            BookmarkSelect,
            "down",
            fixed(Action::SelectBookmarkDown),
            vec![
                single(KeyDef::Char('j')),
                single(KeyDef::Key(KeyCode::Down)),
            ],
        ),
        BindingSpec::new(
            BookmarkSelect,
            "up",
            fixed(Action::SelectBookmarkUp),
            vec![single(KeyDef::Char('k')), single(KeyDef::Key(KeyCode::Up))],
        ),
        BindingSpec::new(
            BookmarkSelect,
            "select",
            fixed(Action::ConfirmBookmarkSelect),
            vec![single(KeyDef::Key(KeyCode::Enter))],
        ),
        BindingSpec::new(
            BookmarkSelect,
            "cancel",
            fixed(Action::ExitBookmarkMode),
            vec![single(KeyDef::Key(KeyCode::Esc))],
        ),
        BindingSpec::new(
            BookmarkPicker,
            "cancel",
            fixed(Action::ExitBookmarkMode),
            vec![single(KeyDef::Key(KeyCode::Esc))],
        ),
        BindingSpec::new(
            BookmarkPicker,
            "confirm",
            fixed(Action::ConfirmBookmarkPicker),
            vec![single(KeyDef::Key(KeyCode::Enter))],
        ),
        BindingSpec::new(
            BookmarkPicker,
            "down",
            fixed(Action::BookmarkPickerDown),
            vec![single(KeyDef::Key(KeyCode::Down))],
        ),
        BindingSpec::new(
            BookmarkPicker,
            "up",
            fixed(Action::BookmarkPickerUp),
            vec![single(KeyDef::Key(KeyCode::Up))],
        ),
        BindingSpec::new(
            BookmarkPicker,
            "backspace",
            fixed(Action::BookmarkFilterBackspace),
            vec![single(KeyDef::Key(KeyCode::Backspace))],
        ),
        BindingSpec::new(
            BookmarkPicker,
            "type",
            BindingBehavior::Action(BookmarkFilterChar),
            vec![single(KeyDef::AnyChar)],
        ),
        BindingSpec::new(
            PushSelect,
            "cancel",
            fixed(Action::ExitPushSelect),
            vec![single(KeyDef::Key(KeyCode::Esc))],
        ),
        BindingSpec::new(
            PushSelect,
            "push",
            fixed(Action::PushSelectConfirm),
            vec![single(KeyDef::Key(KeyCode::Enter))],
        ),
        BindingSpec::new(
            PushSelect,
            "down",
            fixed(Action::PushSelectDown),
            vec![single(KeyDef::Key(KeyCode::Down))],
        ),
        BindingSpec::new(
            PushSelect,
            "up",
            fixed(Action::PushSelectUp),
            vec![single(KeyDef::Key(KeyCode::Up))],
        ),
        BindingSpec::new(
            PushSelect,
            "toggle",
            fixed(Action::PushSelectToggle),
            vec![single(KeyDef::Char(' '))],
        ),
        BindingSpec::new(
            PushSelect,
            "all",
            fixed(Action::PushSelectAll),
            vec![single(KeyDef::Char('a'))],
        ),
        BindingSpec::new(
            PushSelect,
            "none",
            fixed(Action::PushSelectNone),
            vec![single(KeyDef::Char('n'))],
        ),
        BindingSpec::new(
            PushSelect,
            "backspace",
            fixed(Action::PushSelectFilterBackspace),
            vec![single(KeyDef::Key(KeyCode::Backspace))],
        ),
        BindingSpec::new(
            PushSelect,
            "type",
            BindingBehavior::Action(PushSelectFilterChar),
            vec![single(KeyDef::AnyChar)],
        ),
        BindingSpec::new(
            Conflicts,
            "down",
            fixed(Action::ConflictsDown),
            vec![
                single(KeyDef::Char('j')),
                single(KeyDef::Key(KeyCode::Down)),
            ],
        ),
        BindingSpec::new(
            Conflicts,
            "up",
            fixed(Action::ConflictsUp),
            vec![single(KeyDef::Char('k')), single(KeyDef::Key(KeyCode::Up))],
        ),
        BindingSpec::new(
            Conflicts,
            "jump",
            fixed(Action::ConflictsJump),
            vec![single(KeyDef::Key(KeyCode::Enter))],
        ),
        BindingSpec::new(
            Conflicts,
            "resolve",
            fixed(Action::StartResolveFromConflicts),
            vec![single(KeyDef::Char('R'))],
        ),
        BindingSpec::new(
            Conflicts,
            "exit",
            fixed(Action::ExitConflicts),
            vec![single(KeyDef::Char('q')), single(KeyDef::Key(KeyCode::Esc))],
        ),
        BindingSpec::new(
            ClipboardBranchSelect,
            "cancel",
            fixed(Action::ExitClipboardMode),
            vec![single(KeyDef::Char('q')), single(KeyDef::Key(KeyCode::Esc))],
        ),
        BindingSpec::new(
            ClipboardBranchSelect,
            "type",
            BindingBehavior::Action(super::super::ActionTemplate::ClipboardBranchSelectChar),
            vec![single(KeyDef::AnyChar)],
        ),
    ]
}
